//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.269
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClarolineApp.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLanguage() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClarolineApp.Languages.AppLanguage", typeof(AppLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publiée le {0}.
        /// </summary>
        public static string AnnoncePage_DateFormater_Published {
            get {
                return ResourceManager.GetString("AnnoncePage_DateFormater_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annonces.
        /// </summary>
        public static string CoursPage_Ann_PI {
            get {
                return ResourceManager.GetString("CoursPage_Ann_PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Documents.
        /// </summary>
        public static string CoursPage_Doc_PI {
            get {
                return ResourceManager.GetString("CoursPage_Doc_PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;authentification a échoué.
        /// </summary>
        public static string ErrorMessage_AuthFailed {
            get {
                return ResourceManager.GetString("ErrorMessage_AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le cours doit être rechargé avant de pouvoir effectuer cette action.
        /// </summary>
        public static string ErrorMessage_LoadCourseNeeded {
            get {
                return ResourceManager.GetString("ErrorMessage_LoadCourseNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un accès à internet est nécessaire pour réaliser cette action. Veuillez vous connecter avant de réessayer.
        /// </summary>
        public static string ErrorMessage_NetworkUnavailable {
            get {
                return ResourceManager.GetString("ErrorMessage_NetworkUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiants absents !.
        /// </summary>
        public static string ErrorMessage_NoLogin_Caption {
            get {
                return ResourceManager.GetString("ErrorMessage_NoLogin_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun compte n&apos;est configuré dans les paramètres. Vous devez entrer vos identifiants avant de pouvoir utiliser l&apos;application. Le faire maintenant ?.
        /// </summary>
        public static string ErrorMessage_NoLogin_Message {
            get {
                return ResourceManager.GetString("ErrorMessage_NoLogin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le serveur a retourné le code d&apos;erreur suivant : {0}. {1}.
        /// </summary>
        public static string ErrorMessage_ServerReturnCode {
            get {
                return ResourceManager.GetString("ErrorMessage_ServerReturnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le serveur a retourné une réponse illisible. Si l&apos;erreur se reproduit, veuillez contacter les développeurs..
        /// </summary>
        public static string ErrorMessage_UnreadableJson {
            get {
                return ResourceManager.GetString("ErrorMessage_UnreadableJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auteur.
        /// </summary>
        public static string MainPage_About_Author {
            get {
                return ResourceManager.GetString("MainPage_About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bugs, idées &amp; suggestions ?.
        /// </summary>
        public static string MainPage_About_DevMailButton {
            get {
                return ResourceManager.GetString("MainPage_About_DevMailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ouvrir dans IE.
        /// </summary>
        public static string MainPage_About_IEButton {
            get {
                return ResourceManager.GetString("MainPage_About_IEButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos de.
        /// </summary>
        public static string MainPage_About_PI {
            get {
                return ResourceManager.GetString("MainPage_About_PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remerciements.
        /// </summary>
        public static string MainPage_About_Thanks {
            get {
                return ResourceManager.GetString("MainPage_About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Georges-Henri Leclercq
        ///Pr. Kim Mens (UCL)
        ///Claroline Dev Team.
        /// </summary>
        public static string MainPage_About_ThanksText {
            get {
                return ResourceManager.GetString("MainPage_About_ThanksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        public static string MainPage_About_Version {
            get {
                return ResourceManager.GetString("MainPage_About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer un e-mail aux titulaires.
        /// </summary>
        public static string MainPage_Cours_ContextMenuItem_Mail {
            get {
                return ResourceManager.GetString("MainPage_Cours_ContextMenuItem_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cours.
        /// </summary>
        public static string MainPage_Cours_PI {
            get {
                return ResourceManager.GetString("MainPage_Cours_PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une nouvelle annonce a été publiée..
        /// </summary>
        public static string MainPage_Notif_AddAnn {
            get {
                return ResourceManager.GetString("MainPage_Notif_AddAnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le document {0} a été ajouté dans le dossier {1}.
        /// </summary>
        public static string MainPage_Notif_AddDoc {
            get {
                return ResourceManager.GetString("MainPage_Notif_AddDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une annonce a été mise à jour..
        /// </summary>
        public static string MainPage_Notif_OldAnn {
            get {
                return ResourceManager.GetString("MainPage_Notif_OldAnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le document {0} a été mis à jour..
        /// </summary>
        public static string MainPage_Notif_OldDoc {
            get {
                return ResourceManager.GetString("MainPage_Notif_OldDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notifications.
        /// </summary>
        public static string MainPage_Notif_PI {
            get {
                return ResourceManager.GetString("MainPage_Notif_PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion....
        /// </summary>
        public static string ProgressBar_Connecting {
            get {
                return ResourceManager.GetString("ProgressBar_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Récupération des résultats : {0}.
        /// </summary>
        public static string ProgressBar_ProcessResult {
            get {
                return ResourceManager.GetString("ProgressBar_ProcessResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour....
        /// </summary>
        public static string ProgressBar_Update {
            get {
                return ResourceManager.GetString("ProgressBar_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utiliser le réseau
        ///cellulaire.
        /// </summary>
        public static string SettingsPage_Config_CellularData {
            get {
                return ResourceManager.GetString("SettingsPage_Config_CellularData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        public static string SettingsPage_Config_PI {
            get {
                return ResourceManager.GetString("SettingsPage_Config_PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres avancés.
        /// </summary>
        public static string SettingsPage_Platform_AdvancedSwitch {
            get {
                return ResourceManager.GetString("SettingsPage_Platform_AdvancedSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page de connexion.
        /// </summary>
        public static string SettingsPage_Platform_AuthPage {
            get {
                return ResourceManager.GetString("SettingsPage_Platform_AuthPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Établissement.
        /// </summary>
        public static string SettingsPage_Platform_Institute {
            get {
                return ResourceManager.GetString("SettingsPage_Platform_Institute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de la plateforme.
        /// </summary>
        public static string SettingsPage_Platform_Name {
            get {
                return ResourceManager.GetString("SettingsPage_Platform_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plateforme.
        /// </summary>
        public static string SettingsPage_Platform_PI {
            get {
                return ResourceManager.GetString("SettingsPage_Platform_PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse de la plateforme.
        /// </summary>
        public static string SettingsPage_Platform_URL {
            get {
                return ResourceManager.GetString("SettingsPage_Platform_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin du WebService.
        /// </summary>
        public static string SettingsPage_Platform_WebServicePath {
            get {
                return ResourceManager.GetString("SettingsPage_Platform_WebServicePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string SettingsPage_User_ConnectButton {
            get {
                return ResourceManager.GetString("SettingsPage_User_ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string SettingsPage_User_FirstName {
            get {
                return ResourceManager.GetString("SettingsPage_User_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string SettingsPage_User_LastName {
            get {
                return ResourceManager.GetString("SettingsPage_User_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matricule.
        /// </summary>
        public static string SettingsPage_User_NOMA {
            get {
                return ResourceManager.GetString("SettingsPage_User_NOMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string SettingsPage_User_Password {
            get {
                return ResourceManager.GetString("SettingsPage_User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur.
        /// </summary>
        public static string SettingsPage_User_PI {
            get {
                return ResourceManager.GetString("SettingsPage_User_PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        public static string SettingsPage_User_Username {
            get {
                return ResourceManager.GetString("SettingsPage_User_Username", resourceCulture);
            }
        }
    }
}
